---
# Barebone Snakemake Pipeline
#   for ATAC-seq with paired-end sequencing
# Configuration
# Ye Yuan (yeyu@umich.edu)
# August, 2022


# Whether to work on `original` or `trimmed` fastq for processing steps
trim_type: "trimmed"

# Genome index to use under processed/index
#   will generate index according to workflow/align_makeIndex.smk if specified index does not exist.
#   ... to configure index generation, modify workflow/align_makeIndex.smk.
genome_name: "dm6"

# Post-alignment filters
post_align_filters:
  # Configurable filter: by FLAG, by minimum quality, and removing mito reads
  flag: 2  # Default 0x2 is proper pair
  min_quality: 30
  mito: "chrM"

peak_calling:
  # Configuring MACS2 callpeak
  #   Effective genome size Galaxy references:
  #     Human 2.7e9, Mouse 1.87e9, Fly 1.2e8, C. elegans 9e7
  #   Shift and extension:
  #     For PE50 use shift = -100, extension_size = 200
  # You can control whether to run conversion from bedgraph to bigwig; TODO: CONFIGURE THE RULE IN `callpeak.smk`.
  effective_genome_size: "1.2e8"
  shift: "-100"
  extension_size: "200"
  convertBW: true

# Resource allocation
resources:
  mem_mb:
    fastqc: 16000
    trim: 16000
    align: 32000
    summarize_postalign: 16000
    peak_calling: 16000
  threads:
    fastqc: 16
    trim: 16
    align: 32
    summarize_postalign: 16
    peak_calling: 1

# ------------ PIPELINE-SPECIFIC CONFIGURATIONS -----------